import type { HistoricalParallel } from './types';

export const HISTORICAL_PARALLELS: HistoricalParallel[] = [
  {
    id: 'hist_1906',
    text: 'In 1906, Iran became one of the first nations in Asia to adopt a constitution. The Constitutional Revolution taught us that a king must serve under the law, not above it. What you see here is the continuation of that revolution, encoded in a language that cannot be ignored.',
    matchKeywords: ['constitution', 'amendment', 'enacted'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_white_revolution',
    text: 'My father launched the White Revolution in 1963: land reform, literacy, women\'s suffrage, industrialization. It was governance by decree, and decree is fragile. What if those reforms had been encoded on-chain, where no successor could undo them with a pen stroke?',
    matchKeywords: ['reform', 'modernization', 'education'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_1953',
    text: 'In 1953, the constitutional crisis between the Shah and Mossadegh showed what happens when the line between Crown and executive blurs. This system draws that line in Solidity: the Crown nominates but cannot govern, and the PM governs but cannot outlast Parliament\'s confidence.',
    matchKeywords: ['formation', 'confidence', 'pm seated'],
    marker: 'exec',
    once: true,
  },
  {
    id: 'hist_1979',
    text: 'In 1979, I learned the hardest lesson of all: that a constitution on paper is worth nothing if the people feel excluded from it. This is why we build governance in transparent code, why every citizen can verify every vote, why no process can be hidden in a ministry basement.',
    matchKeywords: ['disaster', 'revolution', 'suspended', '1979'],
    marker: 'crown',
    once: true,
  },
  {
    id: 'hist_majlis_first',
    text: 'The first Majlis convened in 1906 in a garden in Tehran, with members chosen by guilds and merchants. From that garden to this simulation, the principle remains: the people must have a house where their voice has the force of law.',
    matchKeywords: ['majlis', 'parliament', 'election'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_judiciary',
    text: 'Iran\'s judicial tradition stretches back to Cyrus the Great and the first declaration of human rights. A constitutional court is not a Western import. It is a return to the principle that even the king of kings must answer to a law higher than his own will.',
    matchKeywords: ['court', 'justice', 'constitutional review'],
    marker: 'court',
    once: true,
  },
  {
    id: 'hist_oil_nationalization',
    text: 'When Mossadegh nationalized Iranian oil, Parliament was the instrument. The Majlis passed the law; the PM executed it. That is how it should work: the people\'s representatives make the decision, and the executive carries it out.',
    matchKeywords: ['enacted', 'signed', 'law'],
    marker: 'crown',
    once: true,
  },
  {
    id: 'hist_dam_building',
    text: 'My father built the Karaj Dam in 1961, the Dez Dam in 1963. Infrastructure that still serves Iran today. The lesson: when a government invests its budget transparently and well, the people reap benefits for generations.',
    matchKeywords: ['budget', 'allocated', 'fiscal'],
    marker: 'budget',
    once: true,
  },
  {
    id: 'hist_succession_qajar',
    text: 'The Qajar dynasty fell because succession was a matter of palace intrigue and foreign meddling. Reza Shah founded our dynasty because the Qajars could not govern. Succession encoded on-chain removes intrigue entirely: the list is public, the rules are immutable.',
    matchKeywords: ['succession', 'heir', 'coronation'],
    marker: 'crown',
    once: true,
  },
  {
    id: 'hist_provincial',
    text: 'Iran\'s provinces are not administrative conveniences. They are histories: Azerbaijan\'s Turkic heritage, Kurdistan\'s ancient mountains, Isfahan\'s Safavid splendor, Khuzestan\'s oil wealth. A Senate that represents provinces ensures that Tehran cannot forget the rest of Iran.',
    matchKeywords: ['senate', 'province', 'provincial'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_1979_court',
    text: 'After 1979, the revolutionary courts bypassed all due process. Trials lasted minutes. Appeals were fiction. A constitutional court with life-tenured justices and transparent rulings is the antidote to revolutionary justice.',
    matchKeywords: ['justice', 'appointed', 'court'],
    marker: 'court',
    once: true,
  },
  {
    id: 'hist_free_press',
    text: 'My father censored the press because he feared criticism. I inherited that fear. A governance system where every vote, every budget line, every judicial ruling is transparent on-chain makes censorship pointless. The truth is already public.',
    matchKeywords: ['transparency', 'audit', 'public'],
    marker: 'budget',
    once: true,
  },
  {
    id: 'hist_reza_shah_modernize',
    text: 'Reza Shah built the Trans-Iranian Railway and founded Tehran University in a single generation. Modernization is in our blood. The question was never whether Iran could build modern institutions, but whether those institutions could survive the death of their builder.',
    matchKeywords: ['minister', 'formation', 'cabinet'],
    marker: 'exec',
    once: true,
  },
  {
    id: 'hist_savak',
    text: 'SAVAK was my greatest failure: a security apparatus that answered to no court and no parliament. The lesson I carry into this design is that every institution must have a check, every power a limit, every official an accountability mechanism encoded in immutable rules.',
    matchKeywords: ['no-confidence', 'oversight', 'crisis'],
    marker: 'exec',
    once: true,
  },
  {
    id: 'hist_cyrus_cylinder',
    text: 'The Cyrus Cylinder, 2,500 years old, proclaimed the rights of conquered peoples to their own customs and religions. Iran invented constitutional thinking before the word existed. What we build here is not borrowed from the West. It is a homecoming.',
    matchKeywords: ['rights', 'constitution', 'enacted'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_women_vote',
    text: 'Iranian women gained the right to vote in 1963, part of my father\'s White Revolution. In this system, every citizen\'s vote carries equal weight, verified by cryptographic proof, counted by code that does not know gender.',
    matchKeywords: ['election', 'vote', 'tallied'],
    marker: 'election',
    once: true,
  },
  {
    id: 'hist_assembly_experts',
    text: 'In 1979, the Assembly of Experts wrote a constitution in weeks that concentrated power in one man. Our approach is different: the constitution is code, every clause testable, every power limited by a deadline and a failsafe. The difference between aspiration and machinery.',
    matchKeywords: ['amendment', 'proposed', 'referendum'],
    marker: 'parl',
    once: true,
  },
  {
    id: 'hist_nuclear_program',
    text: 'In the 1970s, Iran had a civilian nuclear program, a space program, a vision for technological independence. Governance technology is the next frontier. If Iran can build reactors, it can build governance systems that outlast any individual ruler.',
    matchKeywords: ['technology', 'innovation', 'modern'],
    marker: 'budget',
    once: true,
  },
  {
    id: 'hist_no_confidence_1953',
    text: 'In 1953, when the Shah tried to dismiss Mossadegh without Parliament\'s consent, it triggered a constitutional crisis. Here, the process is clear: the Majlis votes no-confidence, the PM falls, and the constitution requires a new formation. No ambiguity, no crisis.',
    matchKeywords: ['no-confidence', 'dismissed', 'resigned'],
    marker: 'exec',
    once: true,
  },
  {
    id: 'hist_death_of_shah',
    text: 'When I died in exile in Cairo in 1980, there was no orderly transition, no constitutional machinery to preserve what we had built. That is the cruelest lesson: all of it, the dams, the universities, the industry, swept away because the transition was not encoded in law.',
    matchKeywords: ['died', 'succession', 'monarch'],
    marker: 'crown',
    once: true,
  },
];
